version: '3.5'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_redis_password


  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - 6380-6390:6379
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_redis_password
      - REDIS_PASSWORD=my_redis_password